name: embed
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: Superalexandre
          repo: game-bot
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_languages: yes
          token: ${{ secrets.METRICS_TOKEN }}
