name: embed
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: classic
          user: Superalexandre
          repo: game-bot
          token: ${{ secrets.METRICS_TOKEN }}