name: embed
on:
  push:
    branches:
      - main
      - dev

index: 1
supports:
  - repository

formats:
  - svg

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          template: repository
          user: Superalexandre
          repo: game-bot
          token: ${{ secrets.METRICS_TOKEN }}